db:
  type: mysql
  #  uri: "root:111111@tcp(106.15.178.205:3306)/qlteam?charset=utf8&parseTime=true"
  uri: "root:111111@tcp(65.49.219.122:3306)/qlteam?charset=utf8&parseTime=true"
  log: true

app:
  port: 9900


token:
  sign: qlteam